# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "seltek:3306"
my_user = "root"
my_pass = "root"
my_charset = "utf8"

# Elasticsearch address
es_addr = "127.0.0.1:9200"
# Elasticsearch user and password, maybe set by shield, nginx, or x-pack
es_user = ""
es_pass = ""

# Path to store data, like master.info, if not set or empty,
# we must use this to support breakpoint resume syncing.
# TODO: support other storage, like etcd.
data_dir = "/data/go-es-data"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# if we have no privilege to use mysqldump with --master-data,
# we must skip it.
#skip_master_data = false

# minimal items to be inserted in one bulk
bulk_size = 128

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "200ms"

is_cron = false
start_cron = "0 * 20 * * *"
stop_cron = "30 * 20 * * *"

# MySQL data source
[[source]]
schema = "beta"
tables = ["member", "order_header", "member_points_item", "order_coupon", "coupon_instance", "member_account"]

[[source]]
schema = "wxy"
tables = ["member", "order_header", "member_points_item", "order_coupon", "coupon_instance", "member_account"]

# Below is for special rule mapping

# Very simple example
#
# desc t;
# +-------+--------------+------+-----+---------+-------+
# | Field | Type         | Null | Key | Default | Extra |
# +-------+--------------+------+-----+---------+-------+
# | id    | int(11)      | NO   | PRI | NULL    |       |
# | name  | varchar(256) | YES  |     | NULL    |       |
# +-------+--------------+------+-----+---------+-------+
#
# The table `t` will be synced to ES index `test` and type `t`.
[[rule]]
schema = "beta"
table = "member"
index = "data"
type = "member"
filter = ["MEMBER_ID", "CHANNEL_ID", "GRADE_ID", "MEMBER_CODE", "EMAIL", "MOBILE", "MEMBER_NAME", "GENDER", "BIRTHDAY", "REGISTER_TIME", "STATUS_ID", "SYSTEM_ID"]
id = ["SYSTEM_ID", "MEMBER_ID"]
extension = "SYSTEM_ID:dq"

[[rule]]
schema = "beta"
table = "order_header"
index = "data"
type = "order"
parent = ["SYSTEM_ID", "MEMBER_ID"]
filter = ["ORDER_ID", "ORDER_CODE", "EXTERNAL_ID", "MEMBER_ID", "CHANNEL_ID", "STORE_ID", "STORE_CODE", "ORDER_DATE", "ORDER_AMOUNT", "PAY_AMOUNT", "USED_POINTS", "CREATE_TIME", "STATUS_ID", "SYSTEM_ID"]
id = ["SYSTEM_ID", "ORDER_ID"]
extension = "SYSTEM_ID:dq"

[[rule]]
schema = "beta"
table = "member_points_item"
index = "data"
type = "points"
parent = ["SYSTEM_ID", "MEMBER_ID"]
filter = ["MEMBER_POINTS_ITEM_ID", "MEMBER_ID", "POINTS_TYPE_ID", "ACTIVITY_INSTANCE_ID", "ITEM_POINTS_NUMBER", "AVAILABLE_POINTS_NUMBER", "CREATE_TIME", "INVALID_DATE", "POINTS_BALANCE", "POINTS_REASON", "STATUS_ID", "ORDER_ID", "EXTERNAL_ID", "SYSTEM_ID"]
id = ["SYSTEM_ID", "MEMBER_POINTS_ITEM_ID"]
extension = "SYSTEM_ID:dq"

[[rule]]
schema = "beta"
table = "order_coupon"
index = "data"
type = "ocoupon"
parent = ["SYSTEM_ID", "ORDER_ID"]
filter = ["ORDER_COUPON_ID", "ORDER_ID", "ORDER_ITEM_ID", "COUPON_INSTANCE_ID", "COUPON_PERCENTAGE", "COUPON_AMOUNT", "SYSTEM_ID"]
id = ["SYSTEM_ID", "ORDER_COUPON_ID"]
extension = "SYSTEM_ID:dq"

[[rule]]
schema = "beta"
table = "coupon_instance"
index = "data"
type = "cinstance"
parent = ["SYSTEM_ID", "COUPON_INSTANCE_OWNER"]
filter = ["COUPON_INSTANCE_ID", "COUPON_ID", "COUPON_NAME", "STATUS_ID", "GET_CHANNEL_ID", "USE_CHANNEL_ID", "STORE_ID", "USE_STORE_CODE", "EXTERNAL_ID", "COUPON_INSTANCE_CODE", "COUPON_INSTANCE_OWNER", "COUPON_INSTANCE_USER", "CREATE_TIME", "GET_TIME", "START_DATE","EXPIRE_DATE", "ACTIVITY_INSTANCE_ID", "ORDER_ID", "SYSTEM_ID"]
id = ["SYSTEM_ID", "COUPON_INSTANCE_ID"]
extension = "SYSTEM_ID:dq"

[[rule]]
schema = "beta"
table = "member_account"
index = "data"
type = "account"
parent = ["SYSTEM_ID", "MEMBER_ID"]
filter = ["MEMBER_ACCOUNT_ID", "MEMBER_ID", "ACCOUNT_BALANCE", "POINTS_BALANCE", "TOTAL_CONSUMPTION", "TOTAL_CONSUMPTION_COUNT", "TOTAL_TAKEAWAY_AMOUT", "TOTAL_TAKEAWAY_COUNT", "TOTAL_ACCOUNT", "TOTAL_POINTS", "LAST_ACCOUNT_TIME", "LAST_POINTS_TIME", "SYSTEM_ID"]
id = ["SYSTEM_ID", "MEMBER_ACCOUNT_ID"]
extension = "SYSTEM_ID:dq"

[[rule]]
schema = "wxy"
table = "member"
index = "data"
type = "member"
filter = ["MEMBER_ID", "CHANNEL_ID", "GRADE_ID", "MEMBER_CODE", "EMAIL", "MOBILE", "MEMBER_NAME", "GENDER", "BIRTHDAY", "REGISTER_TIME", "STATUS_ID", "SYSTEM_ID"]
id = ["SYSTEM_ID", "MEMBER_ID"]
extension = "SYSTEM_ID:wxy"

[[rule]]
schema = "wxy"
table = "order_header"
index = "data"
type = "order"
parent = ["SYSTEM_ID", "MEMBER_ID"]
filter = ["ORDER_ID", "ORDER_CODE", "EXTERNAL_ID", "MEMBER_ID", "CHANNEL_ID", "STORE_ID", "STORE_CODE", "ORDER_DATE", "ORDER_AMOUNT", "PAY_AMOUNT", "USED_POINTS", "CREATE_TIME", "STATUS_ID", "SYSTEM_ID"]
id = ["SYSTEM_ID", "ORDER_ID"]
extension = "SYSTEM_ID:wxy"

[[rule]]
schema = "wxy"
table = "member_points_item"
index = "data"
type = "points"
parent = ["SYSTEM_ID", "MEMBER_ID"]
filter = ["MEMBER_POINTS_ITEM_ID", "MEMBER_ID", "POINTS_TYPE_ID", "ACTIVITY_INSTANCE_ID", "ITEM_POINTS_NUMBER", "AVAILABLE_POINTS_NUMBER", "CREATE_TIME", "INVALID_DATE", "POINTS_BALANCE", "POINTS_REASON", "STATUS_ID", "ORDER_ID", "EXTERNAL_ID", "SYSTEM_ID"]
id = ["SYSTEM_ID", "MEMBER_POINTS_ITEM_ID"]
extension = "SYSTEM_ID:wxy"

[[rule]]
schema = "wxy"
table = "order_coupon"
index = "data"
type = "ocoupon"
parent = ["SYSTEM_ID", "ORDER_ID"]
filter = ["ORDER_COUPON_ID", "ORDER_ID", "ORDER_ITEM_ID", "COUPON_INSTANCE_ID", "COUPON_PERCENTAGE", "COUPON_AMOUNT", "SYSTEM_ID"]
id = ["SYSTEM_ID", "ORDER_COUPON_ID"]
extension = "SYSTEM_ID:wxy"

[[rule]]
schema = "wxy"
table = "coupon_instance"
index = "data"
type = "cinstance"
parent = ["SYSTEM_ID", "COUPON_INSTANCE_OWNER"]
filter = ["COUPON_INSTANCE_ID", "COUPON_ID", "COUPON_NAME", "STATUS_ID", "GET_CHANNEL_ID", "USE_CHANNEL_ID", "STORE_ID", "USE_STORE_CODE", "EXTERNAL_ID", "COUPON_INSTANCE_CODE", "COUPON_INSTANCE_OWNER", "COUPON_INSTANCE_USER", "CREATE_TIME", "GET_TIME", "START_DATE","EXPIRE_DATE", "ACTIVITY_INSTANCE_ID", "ORDER_ID", "SYSTEM_ID"]
id = ["SYSTEM_ID", "COUPON_INSTANCE_ID"]
extension = "SYSTEM_ID:wxy"

[[rule]]
schema = "wxy"
table = "member_account"
index = "data"
type = "account"
parent = ["SYSTEM_ID", "MEMBER_ID"]
filter = ["MEMBER_ACCOUNT_ID", "MEMBER_ID", "ACCOUNT_BALANCE", "POINTS_BALANCE", "TOTAL_CONSUMPTION", "TOTAL_CONSUMPTION_COUNT", "TOTAL_TAKEAWAY_AMOUT", "TOTAL_TAKEAWAY_COUNT", "TOTAL_ACCOUNT", "TOTAL_POINTS", "LAST_ACCOUNT_TIME", "LAST_POINTS_TIME", "SYSTEM_ID"]
id = ["SYSTEM_ID", "MEMBER_ACCOUNT_ID"]
extension = "SYSTEM_ID:wxy"